### PR TITLE
Fix/webapp improvements

### PR DESCRIPTION
**Pull request by roscisz**

### CODE REVIEW

**Comment by roscisz** [comment]
In my environment, Tail mode does not work. After checking the check box, yellow synchronization dialog appears at the bottom for a while, then the Tail mode checkbox becomes unchecked again.

**Comment by jszemplinski** [comment]
Managed to reproduce it, the commit above fixes it. (It seems like @click might have different behaviors across different browsers in regards to their execution order relative to the actual model change. rel: https://stackoverflow.com/questions/51430066/v-model-does-not-get-updated-after-checkbox-clicked/51432277)

**Comment by roscisz** [comment]
Thanks, tail mode indeed works after the fix, but now the Auto-refresh check box has no effect, and stays off after clicking.

**Comment by jszemplinski** [comment]
Seems like it's the same issue, will change it for autorefresh as well

**Pull request merged**
