### PR TITLE
Access control UI

### PR DESCRIPTION
**Pull request by martyole**
These changes add groups and restrictions to Users Overview and info about restrictions for logged user to Reservations Overview.

### CODE REVIEW

**Comment by roscisz** [comment]
Name of the logged in user and TensorHive version moved to the left corner (built using npm 6.14.8):

obraz

Is that intended?

**Comment by roscisz** [comment]
In resource selection, it is hard to distinguish between GPUs:

obraz

Maybe short GPU names with consecutive numbers could be used like in the reservation calendar:

obraz

**Comment by roscisz** [comment]
Maybe it should be possible to view/edit user groups in user edit dialog? Roles are already there.

**Comment by roscisz** [comment]
The user list table requires horizontal scrolling, because the actions are hidden:

obraz

Maybe the user ID column should be thinner? 

BTW instead of user role, user groups would be more informative.

**Comment by martyole** [comment]
> Name of the logged in user and TensorHive version moved to the left corner (built using npm 6.14.8):
> 
> obraz
> 
> Is that intended?

It is not intended. I'm using the same version of npm and I've never experienced this. I was able to reproduce this by deleting use of "version_info" and "user_chip" style classes in TheDash.vue but the changes don't include those. Not sure about the reason of this problem yet.

**Comment by martyole** [comment]
> Maybe it should be possible to view/edit user groups in user edit dialog? Roles are already there.

It is now possible to edit user groups in user edit.

**Comment by martyole** [comment]
> The user list table requires horizontal scrolling, because the actions are hidden:
> 
> obraz
> 
> Maybe the user ID column should be thinner?
> 
> BTW instead of user role, user groups would be more informative.

User ID column is a bit thinner now and the whole table a little wider. Also changed role column to groups.

**Comment by roscisz** [comment]
> > Name of the logged in user and TensorHive version moved to the left corner (built using npm 6.14.8):
> > obraz
> > Is that intended?
> 
> It is not intended. I'm using the same version of npm and I've never experienced this. I was able to reproduce this by deleting use of "version_info" and "user_chip" style classes in TheDash.vue but the changes don't include those. Not sure about the reason of this problem yet.

After a rebuild it is no longer the case, so I suppose we should treat this issue as closed.

**Comment by roscisz** [comment]
> > The user list table requires horizontal scrolling, because the actions are hidden:
> > obraz
> > Maybe the user ID column should be thinner?
> > BTW instead of user role, user groups would be more informative.
> 
> User ID column is a bit thinner now and the whole table a little wider. Also changed role column to groups.

Great, I think it's better now. However, in the Groups column I can see only group IDs, wouldn't the group names be more readable?

**Comment by martyole** [comment]
> > > The user list table requires horizontal scrolling, because the actions are hidden:
> > > obraz
> > > Maybe the user ID column should be thinner?
> > > BTW instead of user role, user groups would be more informative.
> > 
> > 
> > User ID column is a bit thinner now and the whole table a little wider. Also changed role column to groups.
> 
> Great, I think it's better now. However, in the Groups column I can see only group IDs, wouldn't the group names be more readable?

It's a number of groups that the user is a member of. If you hover over this number you can see group names (the same is with users column in groups table). Maybe I should change it to showing group names if there is only 1 or 2 and a number if there is more.

**Comment by roscisz** [comment]
>  Maybe I should change it to showing group names if there is only 1 or 2 and a number if there is more.

I think that would be great!

Additionally, I see minor issues connected with defining schedules:

- if there is an error in creating a schedule defined for a restriction, the restriction is saved, but with no schedules (error message is properly displayed). The error should be detected and the restriction should not be saved
- if I start editing a restriction, then delete it using the action on the list, the editing form should go back to "add restriction" state, instead of "edit restriction" state which would result in a "no such restriction" error after trying to save the edited values
- this probably concerns the access control API: schedules on a given day from 0:00-0:00 are forbidden, because the start hour is the same as end hour. So if I want to grant the user privileges to use certain hardware on Mondays and Tuesdays, I would have to use the following schedules: Mon 0:00 - 23:55, Tue 0:00 - 23:55; However, this does not allow the user to reserve the resources between Mon 23:55 and Tue 0:00; What to do?

**Comment by jszemplinski** [comment]
> this probably concerns the access control API: schedules on a given day from 0:00-0:00 are forbidden, because the start hour is the same as end hour. So if I want to grant the user privileges to use certain hardware on Mondays and Tuesdays, I would have to use the following schedules: Mon 0:00 - 23:55, Tue 0:00 - 23:55; However, this does not allow the user to reserve the resources between Mon 23:55 and Tue 0:00; What to do?

From the backend side schedule between 0:00 and 23:59 on any given day is treated as schedule covering the whole day, so having schedule Mon, Tue 0:00 - 23:59 should deal with the issue. We might either increase the resolution of the datetime picker in the frontend, or if need be treat 23:55 as end of day in the backend and allow users to have their reservations between 23:56 and 23:59. (the first proposal is probably cleaner...)

**Comment by martyole** [comment]
> > Maybe I should change it to showing group names if there is only 1 or 2 and a number if there is more.
> 
Done

> 
> * if there is an error in creating a schedule defined for a restriction, the restriction is saved, but with no schedules (error message is properly displayed). The error should be detected and the restriction should not be saved

Now error message is displayed and the restriction is not saved. Also the time picker doesn't allow now to choose the same start and end time.


> * if I start editing a restriction, then delete it using the action on the list, the editing form should go back to "add restriction" state, instead of "edit restriction" state which would result in a "no such restriction" error after trying to save the edited values

Done

> * this probably concerns the access control API: schedules on a given day from 0:00-0:00 are forbidden, because the start hour is the same as end hour. So if I want to grant the user privileges to use certain hardware on Mondays and Tuesdays, I would have to use the following schedules: Mon 0:00 - 23:55, Tue 0:00 - 23:55; However, this does not allow the user to reserve the resources between Mon 23:55 and Tue 0:00; What to do?

Resolution of time picker was changed to 1 minute and now a 0:00-23:59 schedule allows such reservations.

**Comment by martyole** [comment]
> Maybe short GPU names with consecutive numbers could be used like in the reservation calendar

Done. Resource names should display now as hostname + index number that is the same in the reservation calendar.

**Comment by roscisz** [comment]
Margins between allowed reservation markers seem to get wider and wider:

obraz

like there is some additional +1 in each loop cycle :)

**Comment by roscisz** [comment]
In the calendar view, the new UI displays only reservations that belong to the current user. I checked that the problem is on the UI side, not on backend side. Supposedly it is connected with the code for displaying the available reservation times.

**Comment by roscisz** [comment]
> > * if there is an error in creating a schedule defined for a restriction, the restriction is saved, but with no schedules (error message is properly displayed). The error should be detected and the restriction should not be saved
> 
> Now error message is displayed and the restriction is not saved. Also the time picker doesn't allow now to choose the same start and end time.

Are you sure this has been commited to the current branch? I still have this situation, where restriction is saved, but without schedules with such error message:

obraz

**Review by roscisz — APPROVED** [review]

**Pull request merged**
